# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20181011_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
