# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20181012_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
