# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_auto_20181014_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
