# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_post_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploaded_from',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
