# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0008_auto_20181014_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_address',
        ),
    ]
