# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0009_remove_profile_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='dwf_profile.jpg', upload_to='images/'),
        ),
    ]
